### ISSUE TITLE
Место init в разделе Организация кода

### ISSUE THREAD

**Issue by bystritskiy** [ILYA2606/SwiftUIGuideline#1]
Дописать, где находиться и упомянуть init в этой схеме для наглядности 
_
<img width="849" alt="Screenshot 2021-10-25 at 01 34 37" src="https://user-images.githubusercontent.com/16685049/138615718-d11eb804-dc52-4ea8-b9d5-948ebd23777d.png">

**Comment by ILYA2606** [comment]
Готово
